[package]
name = "butt_os"
version = "1.0.0"
authors = ["Joe Friedl <joe@joefriedl.net>"]

[lib]
crate-type = ["staticlib"]

[dependencies]
rlibc = "0.1.4"
spin = "0.3.4"

[dependencies.multiboot2]
git = "https://github.com/phil-opp/multiboot2-elf64"
